echo off
type out_STRING_1.txt | cmd /k
type out_STRING_2.txt | cmd /k
type out_STRING_3.txt | cmd /k
type out_TOKEN_ARGUMENT_1.txt | cmd /k
type out_TOKEN_ARGUMENT_2.txt | cmd /k
type out_TOKEN_ARGUMENT_3.txt | cmd /k
type out_TOKEN_ARGUMENT_4.txt | cmd /k
type out_TOKEN_COMMAND_1.txt | cmd /k
type out_TOKEN_COMMAND_2.txt | cmd /k
type out_TOKEN_COMMAND_3.txt | cmd /k
type out_TOKEN_MEMBER_1.txt | cmd /k
type out_TOKEN_MEMBER_2.txt | cmd /k
type out_TOKEN_MEMBER_3.txt | cmd /k
type out_TOKEN_MEMBER_4.txt | cmd /k
type out_TOKEN_STRING_1.txt | cmd /k
type out_TOKEN_STRING_2.txt | cmd /k
type out_TOKEN_TYPE_1.txt | cmd /k
type out_TOKEN_TYPE_2.txt | cmd /k
type out_TOKEN_VARIABLE_1.txt | cmd /k
type out_TOKEN_WHITESPACE_1.txt | cmd /k
type Powershell_t1.txt | cmd /k
type String1_LAUNCHER_CLIP+.txt | cmd /k
type String1_LAUNCHER_CLIP++.txt | cmd /k
type String1_LAUNCHER_CMD.txt | cmd /k
type String1_LAUNCHER_MSHTA++.txt | cmd /k
type String1_LAUNCHER_PS.txt | cmd /k
type String1_LAUNCHER_RUNDLL.txt | cmd /k
type String1_LAUNCHER_RUNDLL++.txt | cmd /k
type String1_LAUNCHER_STDIN+.txt | cmd /k
type String1_LAUNCHER_STDIN++.txt | cmd /k
type String1_LAUNCHER_VAR+.txt | cmd /k
type String1_LAUNCHER_VAR++.txt | cmd /k
type String1_LAUNCHER_WMIC.txt | cmd /k
type String1_STRING_1.txt | cmd /k
type String1_STRING_2.txt | cmd /k
type String1_STRING_3.txt | cmd /k
type String1_TOKEN_ARGUMENT_1.txt | cmd /k
type String1_TOKEN_ARGUMENT_2.txt | cmd /k
type String1_TOKEN_ARGUMENT_3.txt | cmd /k
type String1_TOKEN_ARGUMENT_4.txt | cmd /k
type String1_TOKEN_COMMAND_1.txt | cmd /k
type String1_TOKEN_COMMAND_2.txt | cmd /k
type String1_TOKEN_COMMAND_3.txt | cmd /k
type String1_TOKEN_MEMBER_1.txt | cmd /k
type String1_TOKEN_MEMBER_2.txt | cmd /k
type String1_TOKEN_MEMBER_3.txt | cmd /k
type String1_TOKEN_MEMBER_4.txt | cmd /k
type String1_TOKEN_STRING_1.txt | cmd /k
type String1_TOKEN_STRING_2.txt | cmd /k
type String1_TOKEN_TYPE_1.txt | cmd /k
type String1_TOKEN_TYPE_2.txt | cmd /k
type String1_TOKEN_VARIABLE_1.txt | cmd /k
type String1_TOKEN_WHITESPACE_1.txt | cmd /k
type String2_LAUNCHER_CLIP+.txt | cmd /k
type String2_LAUNCHER_CLIP++.txt | cmd /k
type String2_LAUNCHER_CMD.txt | cmd /k
type String2_LAUNCHER_MSHTA++.txt | cmd /k
type String2_LAUNCHER_PS.txt | cmd /k
type String2_LAUNCHER_RUNDLL.txt | cmd /k
type String2_LAUNCHER_RUNDLL++.txt | cmd /k
type String2_LAUNCHER_STDIN+.txt | cmd /k
type String2_LAUNCHER_STDIN++.txt | cmd /k
type String2_LAUNCHER_VAR+.txt | cmd /k
type String2_LAUNCHER_VAR++.txt | cmd /k
type String2_LAUNCHER_WMIC.txt | cmd /k
type String3_LAUNCHER_CLIP+.txt | cmd /k
type String3_LAUNCHER_CLIP++.txt | cmd /k
type String3_LAUNCHER_CMD.txt | cmd /k
type String3_LAUNCHER_MSHTA++.txt | cmd /k
type String3_LAUNCHER_PS.txt | cmd /k
type String3_LAUNCHER_RUNDLL.txt | cmd /k
type String3_LAUNCHER_RUNDLL++.txt | cmd /k
type String3_LAUNCHER_STDIN+.txt | cmd /k
type String3_LAUNCHER_STDIN++.txt | cmd /k
type String3_LAUNCHER_VAR+.txt | cmd /k
type String3_LAUNCHER_VAR++.txt | cmd /k
type String3_LAUNCHER_WMIC.txt | cmd /k
type SyncAppvPublishingServer_STRING_1.txt | cmd /k
type SyncAppvPublishingServer_STRING_2.txt | cmd /k
type SyncAppvPublishingServer_STRING_3.txt | cmd /k
type SyncAppvPublishingServer_t1.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_ARGUMENT_1.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_ARGUMENT_2.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_ARGUMENT_3.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_ARGUMENT_4.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_COMMAND_1.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_COMMAND_2.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_COMMAND_3.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_MEMBER_1.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_MEMBER_2.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_MEMBER_3.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_MEMBER_4.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_STRING_1.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_STRING_2.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_TYPE_1.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_TYPE_2.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_VARIABLE_1.txt | cmd /k
type SyncAppvPublishingServer_TOKEN_WHITESPACE_1.txt | cmd /k

